export { call } from './function/call'
export { bind } from './function/bind'
export { apply } from './function/apply'
export { debounce } from './function/debounce'
export { throttle } from './function/throttle'
export { map, reduce, filter, find, findIndex, every, some } from './array/declare'
export { unique1, unique2, unique3 } from './array/unique'
export { concat } from './array/concat'
export { slice } from './array/slice'
export { flatten1, flatten2, flatten3 } from './array/flatten'
export { compact } from './array/compact'
export { chunk } from './array/chunk'
export { difference } from './array/difference'
export { mergeArray } from './array/mergeArray'